### ISSUE TITLE
Issue with BPListReader?

### ISSUE THREAD

**Issue by chrismessina** [akfreas/emoji-extractor-plus#1]
Whenever I try to run the `extract.py` script within the virtualenv, I'm getting this error:

```
Traceback (most recent call last):
  File "extract.py", line 3, in <module>
    from bplist.bplist import BPListReader
ImportError: No module named bplist.bplist
```

**Comment by chrismessina** [comment]
I was able to install the requirements successfully, from what I can tell:

```
pip3 install -r requirements.pip
Defaulting to user installation because normal site-packages is not writeable
Collecting bplist==1.1
  Using cached bplist-1.1.tar.gz (4.3 kB)
Collecting fonttools==4.22.0
  Using cached fonttools-4.22.0-py3-none-any.whl (850 kB)
Collecting Pillow==8.2.0
  Downloading Pillow-8.2.0-cp38-cp38-macosx_10_10_x86_64.whl (2.8 MB)
     |████████████████████████████████| 2.8 MB 13.4 MB/s
Building wheels for collected packages: bplist
  Building wheel for bplist (setup.py) ... done
  Created wheel for bplist: filename=bplist-1.1-py3-none-any.whl size=4703 sha256=2dd1604a2f4aa005293bb1746b80097ef286ea6547ab686f25982eafd40dc4f3
  Stored in directory: /Users/messina/Library/Caches/pip/wheels/5a/35/4b/d3fcf36ac0998b16847c0b2dc53a6f7a0a457de19bef9458ae
Successfully built bplist
Installing collected packages: Pillow, fonttools, bplist
Successfully installed Pillow-8.2.0 bplist-1.1 fonttools-4.22.0
```

**Comment by chrismessina** [comment]
Hmm. It seems like I'm missing a lot of modules.. ended up running these commands in order to execute the `extract.py` script.

```
pip3 install bplist
pip3 install Image
pip3 install fontTools
```

**Comment by UxFFFD** [comment]
Same over here:

```
🤷🏼‍♂️ ➜  python extract.py
Traceback (most recent call last):
  File "extract.py", line 3, in <module>
    from bplist.bplist import BPListReader
ImportError: No module named bplist.bplist
```

**Comment by akfreas** [comment]
Thanks for reporting that, I wasn't able to reproduce it on my machine unfortunately. But I just modified the shebang in `extract.py` to not specify `python3` but rather just `python`, that could have been causing an issue when loading the modules, since it would have looked for a different binary in your `ENV`. Hopefully that helps!

**Comment by UxFFFD** [comment]
Thanks @akfreas, unfortunately it doesn't solve the issue for me

```
in emoji-extractor-plus on  master
🤷🏼‍♂️ ➜  pip install -r requirements.pip
Requirement already satisfied: bplist==1.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from -r requirements.pip (line 1)) (1.1)
Requirement already satisfied: fonttools==4.22.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from -r requirements.pip (line 2)) (4.22.0)
Requirement already satisfied: Pillow==8.2.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from -r requirements.pip (line 3)) (8.2.0)
in emoji-extractor-plus on  master
🤷🏼‍♂️ ➜  python extract.py
Traceback (most recent call last):
  File "extract.py", line 3, in <module>
    from bplist.bplist import BPListReader
ImportError: No module named bplist.bplist
in emoji-extractor-plus on  master
🤷🏼‍♂️ ➜
```

**Comment by akfreas** [comment]
@cmdu After the virtualenv is activated, can you try running:

`python3 -m pip install -r requirements.pip`
and then 
`python3 extract.py`

I'm not really sure why this is coming about, also I'm not able to repro it on my machine ¯\_(ツ)_/¯

**Comment by UxFFFD** [comment]
@akfreas it worked that way! 🥳

**Comment by akfreas** [comment]
🙌  excellent! I will update the readme!
