### ISSUE TITLE
Can not identifiy image file

### ISSUE THREAD

**Issue by xvilo** [akfreas/emoji-extractor-plus#4]
Getting the following exception on MacOS: 

```
$ python3 extract.py --ttc_file /extraced/file/from/ios-sim/ios16.4/AppleColorEmoji-160px.ttc 
extracting sbix chunk to file /Users/xvilo/emoji-extractor-plus/AppleColorEmoji-160px.ttc.xml
Traceback (most recent call last):
  File "/Users/xvilo/emoji-extractor-plus/extract.py", line 170, in <module>
    extract_pngs_from_sbix_xml_file(sbix)
  File "/Users/xvilo/emoji-extractor-plus/extract.py", line 96, in extract_pngs_from_sbix_xml_file
    png_image = Image.open(BytesIO(png_data))
  File "/usr/local/lib/python3.10/site-packages/PIL/Image.py", line 2967, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x102181b20>
```

Mainly wanted to report the issue here, don't have the capacity to hunt for a fix atm

**Comment by Aleksandar-Borisov** [comment]
I confirm that I have the same issue.

MacOS Sonoma 14.5 (23F79)

Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by alex-sutr** [comment]
> Getting the following exception on MacOS:
> 
> ```
> $ python3 extract.py --ttc_file /extraced/file/from/ios-sim/ios16.4/AppleColorEmoji-160px.ttc 
> extracting sbix chunk to file /Users/xvilo/emoji-extractor-plus/AppleColorEmoji-160px.ttc.xml
> Traceback (most recent call last):
>   File "/Users/xvilo/emoji-extractor-plus/extract.py", line 170, in <module>
>     extract_pngs_from_sbix_xml_file(sbix)
>   File "/Users/xvilo/emoji-extractor-plus/extract.py", line 96, in extract_pngs_from_sbix_xml_file
>     png_image = Image.open(BytesIO(png_data))
>   File "/usr/local/lib/python3.10/site-packages/PIL/Image.py", line 2967, in open
>     raise UnidentifiedImageError(
> PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x102181b20>
> ```
> 
> Mainly wanted to report the issue here, don't have the capacity to hunt for a fix atm

Have you been able to solve this problem?
